[package]
name = "fibers_transport"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
bytecodec = "0.4"
factory = "0.1"
fibers = "0.1"
futures = "0.1"
trackable = "0.2"
